# Generated by Django 4.2 on 2023-07-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('mob_no', models.CharField(max_length=15)),
                ('adhar_no', models.CharField(max_length=20)),
                ('prep_for', models.CharField(choices=[('Bsc', 'Bsc'), ('IIT', 'IIT'), ('NEET', 'NEET'), ('UPSC', 'UPSC'), ('JEE', 'JEE'), ('SSC', 'SSC'), ('Railway', 'Railway'), ('Banking', 'Banking')], max_length=30)),
                ('shift', models.CharField(choices=[('7am to 12pm', '7am to 12pm'), ('12pm to 5pm', '12pm to 5pm'), ('10pm to 10pm', '10pm to 10pm')], max_length=40)),
                ('date_of_joining', models.DateField()),
                ('mode_of_payment', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'CASH')], max_length=40)),
            ],
        ),
    ]
