# Generated by Django 4.2 on 2023-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
