# Generated by Django 4.2 on 2023-07-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_student_category_alter_student_prep_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('7am to 12pm', '7am to 12pm'), ('12pm to 5pm', '12pm to 5pm'), ('10pm to 10pm', '10pm to 10pm')], max_length=40)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.shift'),
        ),
    ]
