# Generated by Django 4.2 on 2023-07-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_shift_alter_student_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift',
        ),
        migrations.AddField(
            model_name='shift',
            name='time',
            field=models.CharField(blank=True, choices=[('7am_to_12pm', '7am_to_12pm'), ('12pm_to_5pm', '12pm_to_5pm'), ('10pm_to_10pm', '10pm_to_10pm')], max_length=40, null=True),
        ),
    ]
