# Generated by Django 4.2 on 2023-07-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_shift_shift_shift_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.shift'),
        ),
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(blank=True, choices=[('7am_to_12pm', '7am_to_12pm'), ('12pm_to_5pm', '12pm_to_5pm'), ('10pm_to_10pm', '10pm_to_10pm')], max_length=40, null=True),
        ),
    ]
