# Generated by Django 4.2 on 2023-07-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_student_time_alter_student_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='time',
        ),
    ]
