# Generated by Django 4.2 on 2023-07-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_student_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='time',
            field=models.CharField(blank=True, choices=[('7am to 12pm', '7am to 12pm'), ('12pm to 5pm', '12pm to 5pm'), ('10pm to 10pm', '10pm to 10pm')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(blank=True, choices=[('7am to 12pm', '7am to 12pm'), ('12pm to 5pm', '12pm to 5pm'), ('10pm to 10pm', '10pm to 10pm')], max_length=40, null=True),
        ),
    ]
