# Generated by Django 4.2 on 2023-07-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_time_shift_shift_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='shift_title',
            new_name='time',
        ),
    ]
