# Generated by Django 4.2 on 2023-07-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rename_shift_title_shift_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='time',
            new_name='shift_title',
        ),
    ]
