# Generated by Django 4.2 on 2023-07-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_time_shift_shift_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_title',
            field=models.CharField(blank=True, choices=[('7am_to_12pm', '7am_to_12pm'), ('12pm to 5pm', '12pm_to_5pm'), ('5pm_to 10pm', '5pm _to_10pm')], default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.shift'),
        ),
    ]
