# Generated by Django 4.2 on 2023-07-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_shift_shift_title_alter_student_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.shift'),
        ),
    ]
